env: struct_marl

env_args:
  struct_type: "struct"
  n_comp: 2
  discount_reward: 0.95
  custom_param: {}
  state_obs: False
  state_d_rate: False
  state_alphas: False
  obs_d_rate: False
  obs_multiple: False
  obs_all_d_rate: False
  obs_alphas: False
  env_correlation: True
  campaign_cost: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 30
test_greedy: True
t_max: 1000000
