env: struct_marl

env_args:
  struct_type: "struct"
  n_comp: 5
  discount_reward: 0.95
  custom_param:
    k_comp:  4
  state_obs: True
  state_d_rate: True
  state_alphas: True
  obs_d_rate: False
  obs_multiple: False
  obs_all_d_rate: False
  obs_alphas: True
  env_correlation: True
  campaign_cost: False

learner_log_interval: 25000
log_interval: 25000
runner_log_interval: 25000
test_interval: 25000
test_nepisode: 100
test_greedy: True
t_max: 2050000
