# --- IQV specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 200000

runner: "episode"
#batch_size_run: 6

buffer_size: 5000


target_update_interval: 200


agent_output_type: "q"
learner: "maxqv_learner"
mixer: # None: no Qmixer
vmixer: # None: no Vmixer



name: "imaxqv"

use_cuda: False
use_tensorboard: True
